### ISSUE TITLE
Doesn't shutdown properly when closing a xtdb node.

### ISSUE THREAD

**Issue by victorb** [tatut/xtdb-inspector#8]
I didn't do any deeper digging, but it seems like using xtdb-inspector makes the whole problem being unable to close properly, probably because of lingering thread pools or similar.

I spotted the following in the codebase: https://github.com/tatut/xtdb-inspector/blob/8a8ffd7fe6fef5dde6182ed71e7687d70bed74ef/src/xtdb_inspector/metrics.clj#L15

I didn't see any places where you're closing down the thread pool, so my hunch would be that it's the cause of being unable to exit the program normally after closing a xtdb database using xtdb-inspector.

**Comment by tatut** [comment]
Thanks for the report, indeed it wasn't shutdown anywhere.
